
spring:
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/users?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
